### ISSUE TITLE
Using Images/Logos with php-qrcode

### ISSUE THREAD

**Issue by aw029** [chillerlan/php-qrcode#40]
Hi,

is it possible to use a custom image like a logo or anything else and have it as an overlay? If it is possible, it would be great if you could provide an example.

Something like this one: https://stackoverflow.com/questions/45520988/creating-a-qr-code-with-a-centered-logo-in-php-with-php-qr-code-generator or this one 
https://ourcodeworld.com/articles/read/225/how-to-generate-qr-code-with-logo-easily-in-php-automatically

Thank you very much!
Best
Alexander

**Comment by codemasher** [comment]
Hi, #35 is very similar - the only difference is that it's adding a GD text object instead of another image. (see the [QRImageWithText](https://github.com/chillerlan/php-qrcode/blob/master/examples/QRImageWithText.php) [example](https://github.com/chillerlan/php-qrcode/blob/master/examples/imageWithText.php)). If you prefer ImageMagick, you can extend the [QRImagick](https://github.com/chillerlan/php-qrcode/blob/master/src/Output/QRImagick.php) class.

**Comment by aw029** [comment]
Thank you!
