### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by YgorMarcelinodaSilva** [chillerlan/php-qrcode#43]
Parse error: syntax error, unexpected 'SettingsContainerInterface' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in C:\laragon\www\testeqrcode_php\vendor\chillerlan\php-qrcode\src\QRCode.php on line 153

**Comment by codemasher** [comment]
It's not a bug - you're likely running not on PHP 7.4 - it is [caused by](https://github.com/chillerlan/php-qrcode/blob/master/src/QRCode.php#L153) a [typed property](https://wiki.php.net/rfc/typed_properties_v2) which is not supported by older PHP versions (composer should have thrown an error while trying to install on an invalid PHP version).
You can instead use the [3.2 branch](https://github.com/chillerlan/php-qrcode/releases/tag/3.2.2), which is for PHP 7.2+, or an older one which fits your PHP version.
